<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.1 setup script
 * Date: Sun, 27 May 2018 22:09:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['only_db'] = '';
$cfg['Servers'][$i]['hide_db'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'i9}&*gxjTbSi>AoId9fRo]XB_qW!1LD';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LoginCookieValidity'] = 86400;
?>